apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: sqlinstances.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: SQLInstance
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-aws-databasesqlinstance
    step: sqlinstance
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
